// <auto-generated />
namespace CrmBl.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class _09052020_1546 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_09052020_1546));
        
        string IMigrationMetadata.Id
        {
            get { return "202005091247247_09052020_1546"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
